#ifndef _OCTOPOS_IO_H_
#define _OCTOPOS_IO_H_

#define IO_OP_QUERY_ALL_RESOURCES	1
#define IO_OP_CREATE_RESOURCE		2
#define IO_OP_BIND_RESOURCE		3
#define IO_OP_QUERY_STATE		4
#define IO_OP_AUTHENTICATE		5
#define IO_OP_SEND_DATA			6
#define IO_OP_RECEIVE_DATA		7
#define IO_OP_DEAUTHENTICATE		8
#define IO_OP_DESTROY_RESOURCE		9

#endif
