#ifndef __STORAGE_OCTOPOS_CORE_H_
#define __STORAGE_OCTOPOS_CORE_H_

#if defined(ARCH_SEC_HW) && !defined(PROJ_CPP) && !defined(ROLE_INSTALLER)
#define bool _Bool
#define true 1
#define false 0
#endif

#define MAX_PARTITION_NAME_LEN 64

#define STORAGE_BLOCK_SIZE	512  /* bytes */

#ifndef ARCH_SEC_HW
#define STORAGE_BOOT_PARTITION_SIZE			200000
#define STORAGE_UNTRUSTED_ROOT_FS_PARTITION_SIZE	4000000
#else
#define STORAGE_BOOT_PARTITION_SIZE			100000
#define STORAGE_UNTRUSTED_ROOT_FS_PARTITION_SIZE	300000
#define RAM_ROOT_PARTITION_BASE 0x30000000
#define RAM_UNTRUSTED_PARTITION_BASE (RAM_ROOT_PARTITION_BASE + STORAGE_BOOT_PARTITION_SIZE * STORAGE_BLOCK_SIZE)
#define RAM_ENCLAVE_PARTITION_1_BASE (RAM_UNTRUSTED_PARTITION_BASE + STORAGE_UNTRUSTED_ROOT_FS_PARTITION_SIZE * STORAGE_BLOCK_SIZE)
#define RAM_ENCLAVE_PARTITION_2_BASE (RAM_ENCLAVE_PARTITION_1_BASE + 100 * STORAGE_BLOCK_SIZE)
#define RAM_ENCLAVE_PARTITION_3_BASE (RAM_ENCLAVE_PARTITION_2_BASE + 100 * STORAGE_BLOCK_SIZE)
#define RAM_ENCLAVE_PARTITION_4_BASE (RAM_ENCLAVE_PARTITION_3_BASE + 100 * STORAGE_BLOCK_SIZE)
#endif

#endif /* __STORAGE_OCTOPOS_CORE_H_ */
