#ifndef __STORAGE_OCTOPOS_CORE_H_
#define __STORAGE_OCTOPOS_CORE_H_

#include <tpm/hash.h>

#define STORAGE_KEY_SIZE	TPM_EXTEND_HASH_SIZE  /* bytes */

#ifdef ARCH_SEC_HW
#define STORAGE_BLOCK_SIZE	64  /* bytes */
#else
#define STORAGE_BLOCK_SIZE	512  /* bytes */
#endif

#ifdef ARCH_SEC_HW
#define STORAGE_BOOT_PARTITION_SIZE			1000
#define STORAGE_UNTRUSTED_ROOT_FS_PARTITION_SIZE	2048	
#else
#define STORAGE_BOOT_PARTITION_SIZE			200000
#define STORAGE_UNTRUSTED_ROOT_FS_PARTITION_SIZE	4000000
#endif

#endif /* __STORAGE_OCTOPOS_CORE_H_ */
