/* syscall numbers */
#define SYSCALL_REQUEST_ACCESS_SERIAL_OUT	0
#define SYSCALL_REQUEST_ACCESS_KEYBOARD		1
  /* access modes */
  #define ACCESS_UNLIMITED_REVOCABLE	0
  #define ACCESS_LIMITED_IRREVOCABLE	1
#define SYSCALL_WRITE_TO_FILE			2
#define SYSCALL_READ_FROM_FILE			3
#define SYSCALL_WRITE_TO_SHELL			4
#define SYSCALL_READ_FROM_SHELL			5
