/* syscall numbers */
#define SYSCALL_REQUEST_SECURE_SERIAL_OUT	0
#define SYSCALL_REQUEST_SECURE_KEYBOARD		1
#define SYSCALL_INFORM_OS_OF_TERMINATION	2
#define SYSCALL_INFORM_OS_OF_PAUSE		3
#define SYSCALL_WRITE_TO_SHELL			4
#define SYSCALL_READ_FROM_SHELL			5
#define SYSCALL_OPEN_FILE			6
#define SYSCALL_WRITE_TO_FILE			7
#define SYSCALL_READ_FROM_FILE			8
#define SYSCALL_WRITE_FILE_BLOCKS		9
#define SYSCALL_READ_FILE_BLOCKS		10
#define SYSCALL_CLOSE_FILE			11
#define SYSCALL_REMOVE_FILE			12
#define SYSCALL_REQUEST_SECURE_STORAGE		13
#define SYSCALL_REQUEST_SECURE_IPC		14
#define NUM_SYSCALLS				15
