/* syscall numbers */
#define SYSCALL_REQUEST_SECURE_SERIAL_OUT	0
#define SYSCALL_REQUEST_SECURE_KEYBOARD		1
  /* access modes */
  #define ACCESS_UNLIMITED_REVOCABLE	0
  #define ACCESS_LIMITED_IRREVOCABLE	1
#define SYSCALL_INFORM_OS_OF_TERMINATION	2
#define SYSCALL_WRITE_TO_SHELL			3
#define SYSCALL_READ_FROM_SHELL			4
#define SYSCALL_OPEN_FILE			5
#define SYSCALL_WRITE_TO_FILE			6
#define SYSCALL_READ_FROM_FILE			7
#define SYSCALL_CLOSE_FILE			8
