umode:
	g++ -Wall -Werror -I ../include/ -I ../arch/umode/include/ -I ../arch/umode/include/ serial_out.c ../arch/umode/mailbox_interface/mailbox_serial_out.c -o serial_out -lpthread -lrt

clean:
	rm serial_out
