#ifndef __ETHERNET_HW_PARAMS_H_
#define __ETHERNET_HW_PARAMS_H_
//#include "xparameters.h"
//#include <xparameters.h>

#define PLATFORM_EMAC_BASEADDR 0x12000000U
//#define PLATFORM_EMAC_BASEADDR XPAR_ETHERNET_SUBSYSTEM_AXI_ETHERNET_0_BASEADDR

//#define PLATFORM_TIMER_BASEADDR XPAR_ETHERNET_SUBSYSTEM_AXI_TIMER_MB5_BASEADDR
//#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_ETHERNET_SUBSYSTEM_MICROBLAZE_AXI_INTC_ETHERNET_SUBSYSTEM_AXI_TIMER_MB5_INTERRUPT_INTR
//#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_ETHERNET_SUBSYSTEM_MICROBLAZE_AXI_INTC_ETHERNET_SUBSYSTEM_AXI_TIMER_MB5_INTERRUPT_INTR)


#endif

