#ifndef _UMODE_MAILBOX_H_
#define _UMODE_MAILBOX_H_

#define FIFO_OS_OUT		"/tmp/octopos_mailbox_os_out"
#define FIFO_OS_IN		"/tmp/octopos_mailbox_os_in"
#define FIFO_OS_INTR		"/tmp/octopos_mailbox_os_intr"
#define FIFO_KEYBOARD_OUT	"/tmp/octopos_mailbox_keyboard_out"
#define FIFO_KEYBOARD_IN	"/tmp/octopos_mailbox_keyboard_in"
#define FIFO_KEYBOARD_INTR	"/tmp/octopos_mailbox_keyboard_intr"
#define FIFO_SERIAL_OUT_OUT	"/tmp/octopos_mailbox_serial_out_out"
#define FIFO_SERIAL_OUT_IN	"/tmp/octopos_mailbox_serial_out_in"
#define FIFO_SERIAL_OUT_INTR	"/tmp/octopos_mailbox_serial_out_intr"
#define FIFO_STORAGE_OUT	"/tmp/octopos_mailbox_storage_out"
#define FIFO_STORAGE_IN		"/tmp/octopos_mailbox_storage_in"
#define FIFO_STORAGE_INTR	"/tmp/octopos_mailbox_storage_intr"
#define FIFO_NETWORK_OUT	"/tmp/octopos_mailbox_network_out"
#define FIFO_NETWORK_IN		"/tmp/octopos_mailbox_network_in"
#define FIFO_NETWORK_INTR	"/tmp/octopos_mailbox_network_intr"
#define FIFO_BLUETOOTH_OUT	"/tmp/octopos_mailbox_bluetooth_out"
#define FIFO_BLUETOOTH_IN	"/tmp/octopos_mailbox_bluetooth_in"
#define FIFO_BLUETOOTH_INTR	"/tmp/octopos_mailbox_bluetooth_intr"
#define FIFO_RUNTIME1_OUT	"/tmp/octopos_mailbox_runtime1_out"
#define FIFO_RUNTIME1_IN	"/tmp/octopos_mailbox_runtime1_in"
#define FIFO_RUNTIME1_INTR	"/tmp/octopos_mailbox_runtime1_intr"
#define FIFO_RUNTIME2_OUT	"/tmp/octopos_mailbox_runtime2_out"
#define FIFO_RUNTIME2_IN	"/tmp/octopos_mailbox_runtime2_in"
#define FIFO_RUNTIME2_INTR	"/tmp/octopos_mailbox_runtime2_intr"
#define FIFO_UNTRUSTED_OUT	"/tmp/octopos_mailbox_untrusted_out"
#define FIFO_UNTRUSTED_IN	"/tmp/octopos_mailbox_untrusted_in"
#define FIFO_UNTRUSTED_INTR	"/tmp/octopos_mailbox_untrusted_intr"
#define FIFO_TPM_OUT		"/tmp/octopos_mailbox_tpm_out"
#define FIFO_TPM_IN		"/tmp/octopos_mailbox_tpm_in"
#define FIFO_TPM_INTR		"/tmp/octopos_mailbox_tpm_intr"

#endif
